### PR TITLE
Update Course-Structure.md

### PR DESCRIPTION
**Pull request by NimperX**
Hi @dhanushkac,

Hope that we've missed this essential part when discussing the course structure. So I've added it to the PR. Feel free to reject if that feels not necessary.

### CODE REVIEW

**Comment by dhanushkac** [comment]
Good catch. I prefer to have it. Only concern is since we are offering this as a service and we are filling a gap of knowledge, I am not sure we can provide meaningful references. Most of the time it would be official website URL. WDYT?

**Comment by NimperX** [comment]
> 
> 
> Good catch. I prefer to have it. Only concern is since we are offering this as a service and we are filling a gap of knowledge, I am not sure we can provide meaningful references. Most of the time it would be official website URL. WDYT?

Exactly. And we can add if there is a official community support that url too. something like https://community.somthing.com or https://support.something.com

Then people can follow up those links if they need to know some more.

**Comment by dhanushkac** [comment]
How about mentioning them in introduction? Since references refers to a broad range of further knowledge I doubt it is meaningful here. Let's discuss will team 🙂

**Comment by NimperX** [comment]
Sure 😋

**Comment by NimperX** [comment]
@dhanushkac As discussed in the meeting I've updated the course structure. Please review the PR

**Review by dhanushkac — APPROVED** [review]

**Pull request merged**
